"""
Q-Table Visualization Utility for Reinforcement Learning

This module provides comprehensive visualization capabilities for Q-tables generated
by reinforcement learning methods (MonteCarlo, QLearning, SARSA).

Usage Example:
    # Load and visualize a Q-table from MonteCarlo
    from qtable_visualization import QTableVisualizer
    
    # Option 1: Load from file
    viz = QTableVisualizer(filepath='montecarlo_qtable_5x5.npy')
    
    # Option 2: Use existing Q-table array
    import numpy as np
    qtable = np.load('sarsa_qtable_5x5.npy')
    viz = QTableVisualizer(qtable=qtable)
    
    # Create visualizations
    viz.plot_qtable_heatmap(title='SARSA Q-Table')
    viz.plot_max_qvalues(title='Maximum Q-Values per State')
    viz.plot_best_actions(
        action_labels=['Up', 'Down', 'Left', 'Right'],
        title='Best Actions per State'
    )
    
    # Save the current figure
    viz.save_figure('qtable_visualization.png', dpi=300)

Compatible with:
    - MonteCarlo (learning_techniques/MonteCarlo.py)
    - QLearning (learning_techniques/QLearning.py)
    - Sarsa (learning_techniques/Sarsa.py)
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Optional, List, Tuple


class QTableVisualizer:
    """
    A comprehensive Q-table visualization class for reinforcement learning.
    
    This class provides multiple visualization modes for Q-tables generated by
    RL algorithms like MonteCarlo, Q-Learning, and SARSA. It supports loading
    Q-tables from .npy files or accepting them directly as numpy arrays.
    
    Attributes:
        qtable (np.ndarray): The Q-table as a 2D numpy array (states x actions)
        state_size (int): Number of states in the Q-table
        action_size (int): Number of actions in the Q-table
    """
    
    def __init__(self, qtable: Optional[np.ndarray] = None, filepath: Optional[str] = None):
        """
        Initialize the QTableVisualizer with a Q-table array or file path.
        
        Args:
            qtable: Optional numpy array representing the Q-table (shape: states x actions)
            filepath: Optional path to a .npy file containing the Q-table
            
        Raises:
            ValueError: If neither qtable nor filepath is provided, or if both are provided
            FileNotFoundError: If filepath is provided but file doesn't exist
            ValueError: If loaded/provided qtable is not a 2D array
        
        Examples:
            >>> viz = QTableVisualizer(filepath='montecarlo_qtable_5x5.npy')
            >>> viz = QTableVisualizer(qtable=my_qtable_array)
        """
        if qtable is None and filepath is None:
            raise ValueError("Either 'qtable' array or 'filepath' must be provided")
        
        if qtable is not None and filepath is not None:
            raise ValueError("Provide either 'qtable' or 'filepath', not both")
        
        if filepath is not None:
            try:
                self.qtable = np.load(filepath)
                print(f"Successfully loaded Q-table from {filepath}")
            except FileNotFoundError:
                raise FileNotFoundError(f"Q-table file not found: {filepath}")
        else:
            self.qtable = qtable
        
        # Validate Q-table structure
        if not isinstance(self.qtable, np.ndarray):
            raise ValueError("Q-table must be a numpy array")
        
        if self.qtable.ndim != 2:
            raise ValueError(f"Q-table must be 2D array, got shape {self.qtable.shape}")
        
        self.state_size, self.action_size = self.qtable.shape
        print(f"Q-table shape: {self.state_size} states × {self.action_size} actions")
    
    def plot_qtable_heatmap(
        self, 
        title: Optional[str] = None,
        cmap: str = 'viridis',
        annot: bool = True,
        fmt: str = '.2f',
        figsize: Tuple[int, int] = (12, 8)
    ) -> plt.Figure:
        """
        Plot a full heatmap of the Q-table showing all state-action values.
        
        This visualization displays the complete Q-table as a heatmap where:
        - Rows represent states
        - Columns represent actions
        - Colors indicate Q-values (warmer colors = higher values)
        - Optional annotations show exact Q-values in each cell
        
        Args:
            title: Optional title for the plot. Defaults to "Q-Table Heatmap"
            cmap: Matplotlib colormap name (default: 'viridis')
                  Options: 'viridis', 'plasma', 'coolwarm', 'RdYlGn', etc.
            annot: Whether to annotate cells with Q-values (default: True)
            fmt: Format string for annotations (default: '.2f' for 2 decimals)
            figsize: Figure size as (width, height) tuple (default: (12, 8))
            
        Returns:
            matplotlib.figure.Figure: The created figure object
            
        Examples:
            >>> viz.plot_qtable_heatmap(title='Q-Learning Results')
            >>> viz.plot_qtable_heatmap(cmap='coolwarm', annot=False)
        """
        fig, ax = plt.subplots(figsize=figsize)
        
        # Create heatmap
        sns.heatmap(
            self.qtable,
            annot=annot,
            fmt=fmt,
            cmap=cmap,
            cbar_kws={'label': 'Q-Value'},
            ax=ax,
            linewidths=0.5,
            linecolor='gray'
        )
        
        # Set labels and title
        ax.set_xlabel('Actions', fontsize=12, fontweight='bold')
        ax.set_ylabel('States', fontsize=12, fontweight='bold')
        ax.set_title(title or 'Q-Table Heatmap', fontsize=14, fontweight='bold', pad=20)
        
        plt.tight_layout()
        return fig
    
    def plot_max_qvalues(
        self,
        title: Optional[str] = None,
        cmap: str = 'YlOrRd',
        figsize: Tuple[int, int] = (10, 6)
    ) -> plt.Figure:
        """
        Plot the maximum Q-value for each state.
        
        This visualization shows the best possible value achievable from each state
        by taking the optimal action. Useful for understanding state values and
        identifying valuable vs. poor states.
        
        Args:
            title: Optional title for the plot. Defaults to "Maximum Q-Values per State"
            cmap: Matplotlib colormap name (default: 'YlOrRd')
            figsize: Figure size as (width, height) tuple (default: (10, 6))
            
        Returns:
            matplotlib.figure.Figure: The created figure object
            
        Examples:
            >>> viz.plot_max_qvalues(title='State Values')
            >>> viz.plot_max_qvalues(cmap='Greens')
        """
        fig, ax = plt.subplots(figsize=figsize)
        
        # Calculate max Q-value per state
        max_qvalues = np.max(self.qtable, axis=1)
        
        # Create heatmap (reshape to make it horizontal)
        sns.heatmap(
            max_qvalues.reshape(1, -1),
            annot=True,
            fmt='.3f',
            cmap=cmap,
            cbar_kws={'label': 'Maximum Q-Value'},
            ax=ax,
            xticklabels=range(self.state_size),
            yticklabels=['Max Q']
        )
        
        ax.set_xlabel('State', fontsize=12, fontweight='bold')
        ax.set_title(title or 'Maximum Q-Values per State', fontsize=14, fontweight='bold', pad=20)
        
        plt.tight_layout()
        return fig
    
    def plot_best_actions(
        self,
        action_labels: Optional[List[str]] = None,
        title: Optional[str] = None,
        figsize: Tuple[int, int] = (10, 6),
        cmap: str = 'Set3'
    ) -> plt.Figure:
        """
        Plot the best action for each state as determined by the Q-table.
        
        This visualization shows which action has the highest Q-value for each state,
        effectively displaying the learned policy. The color represents the action,
        and annotations show both the action ID and its Q-value.
        
        Args:
            action_labels: Optional list of action names (e.g., ['Up', 'Down', 'Left', 'Right'])
                          If None, actions are labeled as 'Action 0', 'Action 1', etc.
            title: Optional title for the plot. Defaults to "Best Actions per State"
            figsize: Figure size as (width, height) tuple (default: (10, 6))
            cmap: Matplotlib colormap name (default: 'Set3')
            
        Returns:
            matplotlib.figure.Figure: The created figure object
            
        Examples:
            >>> viz.plot_best_actions(action_labels=['Up', 'Down', 'Left', 'Right'])
            >>> viz.plot_best_actions(title='Learned Policy')
        """
        fig, ax = plt.subplots(figsize=figsize)
        
        # Get best action for each state
        best_actions = np.argmax(self.qtable, axis=1)
        best_qvalues = np.max(self.qtable, axis=1)
        
        # Prepare action labels
        if action_labels is None:
            action_labels = [f'Action {i}' for i in range(self.action_size)]
        elif len(action_labels) != self.action_size:
            raise ValueError(f"action_labels must have {self.action_size} elements, got {len(action_labels)}")
        
        # Create annotation text
        annotations = [f"{action_labels[action]}\n(Q={qval:.2f})" 
                      for action, qval in zip(best_actions, best_qvalues)]
        
        # Create heatmap with best actions
        sns.heatmap(
            best_actions.reshape(1, -1),
            annot=np.array(annotations).reshape(1, -1),
            fmt='',
            cmap=cmap,
            cbar=False,
            ax=ax,
            xticklabels=range(self.state_size),
            yticklabels=['Best Action'],
            linewidths=1,
            linecolor='black'
        )
        
        ax.set_xlabel('State', fontsize=12, fontweight='bold')
        ax.set_title(title or 'Best Actions per State', fontsize=14, fontweight='bold', pad=20)
        
        # Add legend
        from matplotlib.patches import Patch
        legend_elements = [Patch(facecolor=plt.cm.get_cmap(cmap)(i / self.action_size), 
                                label=action_labels[i])
                          for i in range(self.action_size)]
        ax.legend(handles=legend_elements, 
                 loc='center left', 
                 bbox_to_anchor=(1.05, 0.5),
                 title='Actions')
        
        plt.tight_layout()
        return fig
    
    def plot_action_distribution(
        self,
        action_labels: Optional[List[str]] = None,
        title: Optional[str] = None,
        figsize: Tuple[int, int] = (12, 8),
        cmap: str = 'coolwarm'
    ) -> plt.Figure:
        """
        Plot heatmap comparing Q-values across all actions for each state.
        
        This is similar to plot_qtable_heatmap but with transposed axes to better
        visualize how action values compare across states.
        
        Args:
            action_labels: Optional list of action names
            title: Optional title for the plot
            figsize: Figure size as (width, height) tuple
            cmap: Matplotlib colormap name (default: 'coolwarm')
            
        Returns:
            matplotlib.figure.Figure: The created figure object
            
        Examples:
            >>> viz.plot_action_distribution(action_labels=['Up', 'Down', 'Left', 'Right'])
        """
        fig, ax = plt.subplots(figsize=figsize)
        
        # Transpose Q-table for better visualization (actions × states)
        qtable_transposed = self.qtable.T
        
        # Prepare action labels
        if action_labels is None:
            action_labels = [f'Action {i}' for i in range(self.action_size)]
        elif len(action_labels) != self.action_size:
            raise ValueError(f"action_labels must have {self.action_size} elements")
        
        # Create heatmap
        sns.heatmap(
            qtable_transposed,
            annot=True,
            fmt='.2f',
            cmap=cmap,
            cbar_kws={'label': 'Q-Value'},
            ax=ax,
            yticklabels=action_labels,
            linewidths=0.5,
            linecolor='gray'
        )
        
        ax.set_xlabel('States', fontsize=12, fontweight='bold')
        ax.set_ylabel('Actions', fontsize=12, fontweight='bold')
        ax.set_title(title or 'Action Distribution Across States', 
                    fontsize=14, fontweight='bold', pad=20)
        
        plt.tight_layout()
        return fig
    
    def save_figure(self, filename: str, dpi: int = 300) -> None:
        """
        Save the current matplotlib figure to a file.
        
        Args:
            filename: Output filename (supports .png, .pdf, .svg, .jpg, etc.)
            dpi: Dots per inch for raster formats (default: 300)
            
        Examples:
            >>> viz.plot_qtable_heatmap()
            >>> viz.save_figure('qtable_heatmap.png', dpi=300)
            >>> viz.save_figure('qtable_heatmap.pdf')  # Vector format
        """
        plt.savefig(filename, dpi=dpi, bbox_inches='tight')
        print(f"Figure saved to {filename}")
    
    def get_statistics(self) -> dict:
        """
        Get statistical summary of the Q-table.
        
        Returns:
            dict: Dictionary containing Q-table statistics including:
                - min: Minimum Q-value
                - max: Maximum Q-value
                - mean: Mean Q-value
                - std: Standard deviation of Q-values
                - median: Median Q-value
                - best_states: States with highest maximum Q-values
                - worst_states: States with lowest maximum Q-values
                
        Examples:
            >>> stats = viz.get_statistics()
            >>> print(f"Mean Q-value: {stats['mean']:.3f}")
        """
        stats = {
            'min': np.min(self.qtable),
            'max': np.max(self.qtable),
            'mean': np.mean(self.qtable),
            'std': np.std(self.qtable),
            'median': np.median(self.qtable),
            'shape': self.qtable.shape,
            'state_size': self.state_size,
            'action_size': self.action_size
        }
        
        # Find best and worst states
        max_qvalues = np.max(self.qtable, axis=1)
        stats['best_states'] = np.argsort(max_qvalues)[-5:][::-1].tolist()  # Top 5
        stats['worst_states'] = np.argsort(max_qvalues)[:5].tolist()  # Bottom 5
        stats['best_state_values'] = max_qvalues[stats['best_states']].tolist()
        stats['worst_state_values'] = max_qvalues[stats['worst_states']].tolist()
        
        return stats
    
    def print_statistics(self) -> None:
        """
        Print a formatted summary of Q-table statistics.
        
        Examples:
            >>> viz.print_statistics()
            Q-Table Statistics:
            ==================
            Shape: 25 states × 4 actions
            Min Q-value: 0.000
            Max Q-value: 0.951
            ...
        """
        stats = self.get_statistics()
        
        print("\nQ-Table Statistics:")
        print("=" * 50)
        print(f"Shape: {stats['state_size']} states × {stats['action_size']} actions")
        print(f"Min Q-value: {stats['min']:.3f}")
        print(f"Max Q-value: {stats['max']:.3f}")
        print(f"Mean Q-value: {stats['mean']:.3f}")
        print(f"Std Q-value: {stats['std']:.3f}")
        print(f"Median Q-value: {stats['median']:.3f}")
        print(f"\nBest states (by max Q-value): {stats['best_states']}")
        print(f"  Values: {[f'{v:.3f}' for v in stats['best_state_values']]}")
        print(f"\nWorst states (by max Q-value): {stats['worst_states']}")
        print(f"  Values: {[f'{v:.3f}' for v in stats['worst_state_values']]}")
        print("=" * 50)


# Convenience function for quick visualization
def visualize_qtable(
    filepath: str,
    action_labels: Optional[List[str]] = None,
    save_prefix: Optional[str] = None
) -> QTableVisualizer:
    """
    Convenience function to quickly load and visualize a Q-table.
    
    This function creates a QTableVisualizer, generates all three main
    visualization types, and optionally saves them to files.
    
    Args:
        filepath: Path to the .npy Q-table file
        action_labels: Optional list of action names
        save_prefix: If provided, saves figures as {save_prefix}_heatmap.png, etc.
        
    Returns:
        QTableVisualizer: The visualizer instance for further customization
        
    Examples:
        >>> viz = visualize_qtable('montecarlo_qtable_5x5.npy', 
        ...                        action_labels=['Up', 'Down', 'Left', 'Right'],
        ...                        save_prefix='mc_viz')
    """
    viz = QTableVisualizer(filepath=filepath)
    viz.print_statistics()
    
    # Create all visualizations
    viz.plot_qtable_heatmap(title=f'Q-Table: {filepath}')
    if save_prefix:
        viz.save_figure(f'{save_prefix}_heatmap.png')
    plt.show()
    
    viz.plot_max_qvalues(title=f'Max Q-Values: {filepath}')
    if save_prefix:
        viz.save_figure(f'{save_prefix}_max_qvalues.png')
    plt.show()
    
    viz.plot_best_actions(action_labels=action_labels, 
                         title=f'Best Actions: {filepath}')
    if save_prefix:
        viz.save_figure(f'{save_prefix}_best_actions.png')
    plt.show()
    
    if action_labels:
        viz.plot_action_distribution(action_labels=action_labels,
                                     title=f'Action Distribution: {filepath}')
        if save_prefix:
            viz.save_figure(f'{save_prefix}_action_dist.png')
        plt.show()
    
    return viz


if __name__ == '__main__':
    # Example usage demonstration
    print(__doc__)
    print("\n" + "=" * 70)
    print("Example: Creating a sample Q-table and visualizing it")
    print("=" * 70)
    
    # Create a sample Q-table (5x5 grid = 25 states, 4 actions)
    np.random.seed(42)
    sample_qtable = np.random.rand(25, 4) * 0.5
    # Make some states clearly better
    sample_qtable[24, :] = [0.9, 0.8, 0.7, 0.95]  # Goal state
    sample_qtable[0, :] = [0.1, 0.05, 0.08, 0.12]  # Start state
    
    viz = QTableVisualizer(qtable=sample_qtable)
    viz.print_statistics()
    
    print("\nCreating visualizations...")
    action_names = ['Up', 'Down', 'Left', 'Right']
    
    viz.plot_qtable_heatmap(title='Sample Q-Table Heatmap')
    plt.show()
    
    viz.plot_max_qvalues(title='Sample Maximum Q-Values')
    plt.show()
    
    viz.plot_best_actions(action_labels=action_names, 
                         title='Sample Best Actions')
    plt.show()
    
    print("\n✓ Visualization demonstration complete!")